[0m23:59:49.030741 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7fc7484168e0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7fc7469f44f0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7fc747b10070>]}


============================== 23:59:49.038790 | 530facf6-2d18-4bdc-8005-60c61f7ab3c1 ==============================
[0m23:59:49.038790 [info ] [MainThread]: Running with dbt=1.7.14
[0m23:59:49.040763 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'log_cache_events': 'False', 'write_json': 'True', 'partial_parse': 'True', 'cache_selected_only': 'False', 'warn_error': 'None', 'version_check': 'True', 'debug': 'False', 'log_path': 'logs', 'profiles_dir': '/home/miki/.dbt', 'fail_fast': 'False', 'use_colors': 'True', 'use_experimental_parser': 'False', 'no_print': 'None', 'quiet': 'False', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'introspect': 'True', 'invocation_command': 'dbt init', 'static_parser': 'True', 'target_path': 'None', 'log_format': 'default', 'send_anonymous_usage_stats': 'True'}
[0m23:59:49.042680 [warn ] [MainThread]: [ConfigFolderDirectory]: Unable to parse dict {'dir': PosixPath('/home/miki/.dbt')}
[0m23:59:49.044162 [info ] [MainThread]: Creating dbt configuration folder at 
[0m00:00:05.495554 [debug] [MainThread]: Starter project path: /home/miki/.local/lib/python3.8/site-packages/dbt/include/starter_project
[0m00:00:05.499975 [info ] [MainThread]: 
Your new dbt project "mikis_dbt" was created!

For more information on how to configure the profiles.yml file,
please consult the dbt documentation here:

  https://docs.getdbt.com/docs/configure-your-profile

One more thing:

Need help? Don't hesitate to reach out to us via GitHub issues or on Slack:

  https://community.getdbt.com/

Happy modeling!

[0m00:00:05.500986 [info ] [MainThread]: Setting up your profile.
[0m00:14:15.640621 [error] [MainThread]: Encountered an error:
list index out of range
[0m00:14:15.645604 [error] [MainThread]: Traceback (most recent call last):
  File "/home/miki/.local/lib/python3.8/site-packages/dbt/cli/requires.py", line 91, in wrapper
    result, success = func(*args, **kwargs)
  File "/home/miki/.local/lib/python3.8/site-packages/dbt/cli/requires.py", line 76, in wrapper
    return func(*args, **kwargs)
  File "/home/miki/.local/lib/python3.8/site-packages/dbt/cli/main.py", line 515, in init
    results = task.run()
  File "/home/miki/.local/lib/python3.8/site-packages/dbt/task/init.py", line 344, in run
    self.setup_profile(profile_name)
  File "/home/miki/.local/lib/python3.8/site-packages/dbt/task/init.py", line 263, in setup_profile
    adapter = self.ask_for_adapter_choice()
  File "/home/miki/.local/lib/python3.8/site-packages/dbt/task/init.py", line 245, in ask_for_adapter_choice
    return available_adapters[numeric_choice - 1]
IndexError: list index out of range

[0m00:14:15.650011 [debug] [MainThread]: Resource report: {"command_name": "init", "command_wall_clock_time": 866.6955, "process_user_time": 2.666019, "process_kernel_time": 0.148277, "process_mem_max_rss": "88400", "process_in_blocks": "44656", "process_out_blocks": "72", "command_success": false}
[0m00:14:15.652616 [debug] [MainThread]: Command `dbt init` failed at 00:14:15.652159 after 866.70 seconds
[0m00:14:15.653782 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7fc7484168e0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7fc7469f46d0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7fc746a35f70>]}
[0m00:14:15.654829 [debug] [MainThread]: Flushing usage events
[0m00:17:01.482808 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7f5d91942c70>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7f5d912292b0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7f5d8ff20d60>]}


============================== 00:17:01.486128 | 9c4eb183-41ce-4aa4-91c1-15c5a04f4d12 ==============================
[0m00:17:01.486128 [info ] [MainThread]: Running with dbt=1.7.14
[0m00:17:01.486886 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'log_cache_events': 'False', 'write_json': 'True', 'partial_parse': 'True', 'cache_selected_only': 'False', 'warn_error': 'None', 'version_check': 'True', 'profiles_dir': '/home/miki/.dbt', 'log_path': 'logs', 'debug': 'False', 'fail_fast': 'False', 'use_colors': 'True', 'use_experimental_parser': 'False', 'no_print': 'None', 'quiet': 'False', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'introspect': 'True', 'invocation_command': 'dbt run', 'static_parser': 'True', 'target_path': 'None', 'log_format': 'default', 'send_anonymous_usage_stats': 'True'}
[0m00:17:01.487579 [error] [MainThread]: Encountered an error:
Runtime Error
  No dbt_project.yml found at expected path /home/miki/Documents/10 Academy/Week 2/Traffic_DWH/my_dbt_project/dbt_project.yml
  Verify that each entry within packages.yml (and their transitive dependencies) contains a file named dbt_project.yml
  
[0m00:17:01.488758 [debug] [MainThread]: Resource report: {"command_name": "run", "command_wall_clock_time": 0.06052727, "process_user_time": 2.303747, "process_kernel_time": 0.093121, "process_mem_max_rss": "88528", "process_in_blocks": "54008", "process_out_blocks": "16", "command_success": false}
[0m00:17:01.489822 [debug] [MainThread]: Command `dbt run` failed at 00:17:01.489626 after 0.06 seconds
[0m00:17:01.490369 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7f5d91942c70>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7f5d912292b0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7f5d8ff20d60>]}
[0m00:17:01.490917 [debug] [MainThread]: Flushing usage events
